name: Deploy Admin Dev Frontend

on:
  push:
    branches: [ dev ,main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        env:
            NODE_ENV: production
  
            # App Settings
            VITE_APP_TITLE: Qallab Admin Dashboard
            VITE_PORT: 3000
  
            # API Settings
            VITE_API_BASE_URL: https://api-dev.qallab.sa/api/admin
  
            # Localization
            VITE_DEFAULT_LOCALE: ar
            VITE_FALLBACK_LOCALE: en
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.SERVER_HOST_PROD }} >> ~/.ssh/known_hosts


      - name: Deploy
        run: |
          SERVER_HOST=$([[ "${{ github.ref_name }}" == "main" ]] && echo "${{ secrets.SERVER_HOST_PROD }}" || echo "${{ secrets.SERVER_HOST }}")

          rsync -avz --delete dist/ \
          ${{ secrets.SERVER_USER }}@$SERVER_HOST:/var/www/frontend/admin-dev.qallab.sa/dist

